Fix decoding w/ arrays
Component can be null, resulting in an empty array being set by default,
but we are not appropriately handling it:

    TypeError: Cannot read properties of undefined (reading 'name')

The newly added test captures this case.